#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use AuthToken\Commands\SecretCommand;
use AuthToken\Commands\MigrationCommand;

$application = new Application();
$application->add(new SecretCommand());
$application->add(new MigrationCommand());
try {
    $application->run();
} catch (Exception $e) {
    error_log($e->getMessage());
}